-- Compute and Database Setup
CREATE WAREHOUSE IF NOT EXISTS AUTOPULSE_WH
    WITH WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS AUTOPULSE_DB;
USE DATABASE AUTOPULSE_DB;

-- Schema Architecture mirroring the Streamlit App
CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS FEATURES;
CREATE SCHEMA IF NOT EXISTS MART;
CREATE SCHEMA IF NOT EXISTS AGENT;
CREATE SCHEMA IF NOT EXISTS SERVICE;

-- Streamlit Deployment Stage
CREATE STAGE IF NOT EXISTS MART.STREAMLIT_STAGE
    DIRECTORY = (ENABLE = TRUE);

-- 1. Fleet Dimension & Real-Time Health Status
CREATE OR REPLACE TABLE MART.DIM_VEHICLE_FLEET_HEALTH (
    VIN VARCHAR(32) PRIMARY KEY,
    MODEL VARCHAR(50) NOT NULL,
    VARIANT VARCHAR(50) NOT NULL,
    MODEL_YEAR VARCHAR(4) NOT NULL,
    CURRENT_ODOMETER_KM NUMBER(10, 0) NOT NULL,
    WARRANTY_STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    HIGHEST_COMPONENT_RISK VARCHAR(20) NOT NULL, -- CRITICAL, HIGH, MEDIUM, LOW
    CRITICAL_COMPONENT_AT_RISK VARCHAR(100),
    MIN_PREDICTED_RUL_DAYS NUMBER(5, 0) NOT NULL,
    PRIMARY_DEALER_ID VARCHAR(32) NOT NULL,
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 2. Daily Sensor Aggregations (14-Day Dual-Trace Telemetry)
CREATE OR REPLACE TABLE FEATURES.VEHICLE_TELEMETRY_DAILY_AGG (
    VIN VARCHAR(32) NOT NULL,
    FEATURE_DATE DATE NOT NULL,
    AVG_BRAKE_TEMP_C FLOAT NOT NULL,
    SEVERE_ROUGHNESS_CYCLES FLOAT NOT NULL,
    AVG_PACK_VOLTAGE FLOAT DEFAULT 398.0,
    INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (VIN, FEATURE_DATE)
);

-- 3. OEM Technical Service Bulletins (TSB RAG Source)
CREATE OR REPLACE TABLE AGENT.OEM_TSB_MANUALS (
    TSB_ID VARCHAR(32) PRIMARY KEY,
    COMPONENT_CATEGORY VARCHAR(100) NOT NULL,
    SYMPTOM_DESCRIPTION TEXT NOT NULL,
    REPAIR_INSTRUCTIONS TEXT NOT NULL,
    SAFETY_WARNINGS TEXT NOT NULL,
    ASIL_RATING VARCHAR(10) DEFAULT 'ASIL-D'
);

-- 4. Service Recommendations Queue
CREATE OR REPLACE TABLE AGENT.SERVICE_RECOMMENDATIONS (
    RECOMMENDATION_ID VARCHAR(64) DEFAULT UUID_STRING() PRIMARY KEY,
    VIN VARCHAR(32) NOT NULL,
    SERVICE_CODE VARCHAR(32) NOT NULL,
    ESTIMATED_COST NUMBER(10, 2) NOT NULL,
    APPROVAL_STATUS VARCHAR(50) DEFAULT 'PENDING_APPROVAL',
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 5. Dealership Maintenance Analytics & Inventory Tracking
CREATE OR REPLACE TABLE MART.FACT_SERVICE_MAINTENANCE_ANALYTICS (
    FACT_ID VARCHAR(64) DEFAULT UUID_STRING() PRIMARY KEY,
    VIN VARCHAR(32) NOT NULL,
    AGGREGATION_DATE DATE DEFAULT CURRENT_DATE(),
    RECOMMENDED_SERVICE_CODE VARCHAR(32),
    ESTIMATED_REPAIR_COST NUMBER(10, 2),
    PART_NUMBER_REQUIRED VARCHAR(32) NOT NULL,
    DEALER_PARTS_ON_HAND NUMBER(5, 0) NOT NULL,
    PRIMARY_DEALER_ID VARCHAR(32) NOT NULL
);

-- 6. Dealership Inventory Master Ledger
CREATE OR REPLACE TABLE SERVICE.DEALERSHIP_INVENTORY (
    DEALER_ID VARCHAR(32) NOT NULL,
    PART_NUMBER VARCHAR(32) NOT NULL,
    STOCK_ON_HAND NUMBER(5, 0) NOT NULL,
    STOCK_RESERVED NUMBER(5, 0) DEFAULT 0,
    PRIMARY KEY (DEALER_ID, PART_NUMBER)
);

-- Seed Initial Knowledge Base & Dealership Stock
INSERT INTO AGENT.OEM_TSB_MANUALS (TSB_ID, COMPONENT_CATEGORY, SYMPTOM_DESCRIPTION, REPAIR_INSTRUCTIONS, SAFETY_WARNINGS)
VALUES 
    ('TSB-2026-INV', 'Inverter Phase B', 'CAN registers indicate persistent high-temperature thermal cycling (>380°C) with asymmetric front-axle heat dissipation.', 'Depressurize electro-hydraulic circuit; install replacement OEM caliper carrier assembly (torque to 115 Nm).', 'Verify high-voltage cutoff interlocks prior to mechanical chassis access.'),
    ('TSB-2026-BRK', 'Brake Actuator', 'Rapid hydraulic pressure dissipation below 750 PSI with severe disc glazing.', 'Depressurize hydraulic circuit; replace Brake Actuator assembly; bleed with DOT 4 Low-Viscosity fluid.', 'Stopping margin compromised. Do not operate on public roads prior to sign-off.');

INSERT INTO SERVICE.DEALERSHIP_INVENTORY (DEALER_ID, PART_NUMBER, STOCK_ON_HAND, STOCK_RESERVED)
VALUES 
    ('DLR-WEST-01', 'INV-8820-T', 4, 1),
    ('DLR-WEST-01', 'BRK-4001-A', 12, 2),
    ('DLR-EAST-02', 'BRK-4001-A', 8, 1),
    ('DLR-CENTRAL-03', 'INV-8820-T', 6, 0);